import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillGithub, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import logo from '../public/logo2.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sprinkels Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">

          {/* nav bar */}
          <nav className="py-10 mb-12 flex justify-between">

            {/* left side nav*/}
            <h1 className="text-xl font-burtons">christian sprinkel</h1>

            {/* right side nav */}
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">resume</a></li>
            </ul>
          </nav>

          {/* opening text */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">BING CHILLING</h2>
            <h3 className="text-2xl py-2">Frontend Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-600">Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu BING CHILLING</p>
          </div>

          {/* socials link */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillInstagram/>
            <AiFillGithub/>
            <AiFillYoutube/>
          </div>

          {/* logo */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={logo} layout="fill" objectFit="cover"/>
          </div>

        </section>
      </main>
    </div>
  )
}