import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillGithub, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import logo from '../public/logo2.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import {useState} from 'react';

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sprinkels Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">

          {/* nav bar */}
          <nav className="py-10 mb-12 flex justify-between dark:text-white">

            {/* left side nav*/}
            <h1 className="text-xl font-burtons">csprinkels</h1>

            {/* right side nav */}
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill 
              onClick={() => setDarkMode(!darkMode)} 
              className="cursor-pointer text-2xl"/>
              </li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">resume</a></li>
            </ul>
          </nav>

          {/* opening text */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">CHRISTIAN SPRINKEL</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Frontend Developer</h3>
            {/* <p className="text-md py-5 leading-8 text-gray-600 dark:text-gray-200 max-w-xl mx-auto md:text-xl">Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu BING CHILLING</p> */}
          </div>

          {/* socials link */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <AiFillInstagram className="cursor-pointer"/>
            <AiFillGithub className="cursor-pointer"/>
            <AiFillYoutube className="cursor-pointer"/>
          </div>

          {/* logo */}
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={logo} layout="fill" objectFit="cover"/>
          </div>

          {/* what i offer */}
          <section>
            <div>
              <h3 className="text-3xl py-1 dark:text-white">what i offer</h3>
              {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu <span className="text-teal-500">BING CHILLING </span>
              wǒ hěn xǐhuān <span className="text-teal-500">BING CHILLING </span>
              dànshì sùdù yǔ jīqíng 9 bǐ <span className="text-teal-500">BING CHILLING </span> 
              sùdù yǔ jīqíng sùdù yǔ jīqíng 9 wǒ zuì xǐhuān
              suǒyǐ…xiànzài shì yīnyuè shíjiān zhǔnbèi
              </p> */}
            </div>

            {/* cards */}
            <div className="lg:flex gap-10">

              {/* design */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <Image class="mx-auto" src={design} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Designs
                </h3>
                {/* <p className="py-2">
                I'll make you the website of your dreams
                </p> */}
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Blender</p>
                <p className="text-gray-800 py-1">Figma</p>
              </div>

              {/* code */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image class="mx-auto" src={code} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Code
                </h3>
                {/* <p className="py-2">
                  Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu <span className="text-teal-500">BING CHILLING </span>
                </p> */}
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">HTML5, CSS3</p>
                <p className="text-gray-800 py-1">ReactJS, Tailwind</p>
                <p className="text-gray-800 py-1">ThreeJS</p>
              </div>

              {/* consulting */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image class="mx-auto" src={consulting} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 ">CHEEE</h3>
                {/* <p className="py-2">
                  Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu <span className="text-teal-500">BING CHILLING </span>
                </p> */}
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
              </div>
            </div>
          </section>

          {/* portfolio */}
          <section className="py-10">
            <div>
              <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu <span className="text-teal-500">BING CHILLING </span>
              wǒ hěn xǐhuān <span className="text-teal-500">BING CHILLING </span>
              dànshì sùdù yǔ jīqíng 9 bǐ <span className="text-teal-500">BING CHILLING </span> 
              sùdù yǔ jīqíng sùdù yǔ jīqíng 9 wǒ zuì xǐhuān
              suǒyǐ…xiànzài shì yīnyuè shíjiān zhǔnbèi
              </p>
            </div>
          </section>
        </section>
      </main>
    </div>
  );
}